### ISSUE TITLE
Task 024: Vista Listado de partidos creados

### ISSUE THREAD

**Issue by paomarsan** [VolleyMate/volleymate#35]

**Comment by meriglmar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VolleyMate-64022bdc64696c002038d91c/issues/VolleyMate/volleymate/35?planning-poker) with Zenhub @abernalmar @anadurlen @angmarnun1 @Ginpasfer @pacoreyes01 @paomarsan @robpazriv
